steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'random_forest'
    args: ['build', '-t',
           'gcr.io/dotted-lens-131912/kfp-pipeline-random-forest:latest',
           '.']
images:
    - 'gcr.io/dotted-lens-131912/kfp-pipeline-random-forest:latest'
