steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'logistic_regression'
    args: ['build', '-t',
           'gcr.io/dotted-lens-131912/kfp-pipeline-logistic_regression:latest', '.']
images:
    - 'gcr.io/dotted-lens-131912/kfp-pipeline-logistic_regression:latest'
